---

services:
  backend:
    build:
      context: ./backend/LakLak-Site
      dockerfile: Dockerfile
    container_name: laklak_backend_container
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data:rw
    networks:
      - laklak_network

  frontend:
    build:
      context: ./frontend
    container_name: laklak_frontend_container
    ports:
      - "3000:3000"
    networks:
      - laklak_network
    depends_on:
      - backend



networks:
  laklak_network:

volumes:
  data: